In [1]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 10)

In [2]:
hospital_df = pd.read_csv("../data/raw/hospital_operations.csv")

patient_df = pd.read_csv("../data/raw/patient_operations.csv")

In [3]:
print("="*60)
print("Hospital Operations Dataset")
print("="*60)
print(hospital_df.shape)

print()

print("="*60)
print("Patient Operations Dataset")
print("="*60)
print(patient_df.shape)

============================================================
Hospital Operations Dataset
============================================================
(500, 21)

============================================================
Patient Operations Dataset
============================================================
(100000, 15)

In [5]:
hospital_df.head()

,Month,Case_No,DOB,Nationality,Gender,DoctorLicense,DoctorName,Doctor Type,Doctor Status,CMI Value,Specialty,Insurance/Payer,InsurancePlanName,Payer Mix,Case type,LOS,Severity,Surgical Mix,Discharge Time,Discharge Before 12PM,Revenue
0,2025-02-01,123517868.0,2002.0,Pakistan,F,ABC123,Dr. Shawn Martin,Consultant,Inactive,1.048,Emergency,PureWin Insurance,Premium,Insurance,OP,0.0,1.0,Medical,07:00:00,Yes,548.0
1,2025-10-01,123810649.0,1981.0,Indonesia,F,VBN123,Dr. Peter Novak,Consultant,Active,0.942,Orthopaedics,PureWin Insurance,Basic,Insurance,OP,0.0,2.0,Medical,NaN,NaN,1198.0
2,2025-08-01,123979661.0,1990.0,Egypt,M,FGH123,Dr. Sofia Kim,GP,Active,1.089,Internal Medicine,PureWin Insurance,Premium,Insurance,OP,0.0,1.0,Medical,NaN,NaN,586.0
3,2025-06-01,123927914.0,1991.0,Germany,M,HJK123,Dr. Priya Iyer,Specialist,Active,0.970,Obstetrics & Gynecology,BlueMedic Charity,NaN,Corporate,IP,5.0,1.0,Medical,09:13:00,Yes,28717.0
4,2025-06-01,123605097.0,2000.0,UAE,F,ABC234,Dr. Thomas Muller,Specialist,Active,1.006,Nephrology,Nextcare Insurance,NC-Blue,Insurance,IP,4.0,3.0,Medical,13:39:00,No,117129.0

In [6]:
patient_df.head()

,Patient_ID,Age,Gender,Department,Diagnosis,Severity_Level,Admission_Date,Discharge_Date,Length_of_Stay_Days,Wait_Time_Minutes,Doctor_ID,Insurance_Type,Treatment_Cost_USD,Readmission_Flag,Outcome
0,PAT000001,23,Male,Gynecology,Cancer,Low,2026-05-02 06:06:47.667330,2026-05-04 06:06:47.667330,2,79,DOC0350,Employer,485,0,Recovered
1,PAT000002,48,Male,Neurology,Kidney Disease,Medium,2026-03-24 15:52:16.633920,2026-03-30 15:52:16.633920,6,167,DOC0267,Private,3487,0,Improved
2,PAT000003,63,Male,Neurology,Stroke,Low,2025-09-07 03:51:37.073134,2025-09-10 03:51:37.073134,3,281,DOC0197,Self-Pay,716,0,Recovered
3,PAT000004,85,Male,Emergency,Asthma,Medium,2024-11-19 00:17:09.630895,2024-11-21 00:17:09.630895,2,271,DOC0009,Government,2111,0,Recovered
4,PAT000005,93,Female,Neurology,Pneumonia,Medium,2024-07-20 04:48:22.195440,2024-07-27 04:48:22.195440,7,112,DOC0219,Self-Pay,4968,0,Transferred

In [7]:
print(hospital_df.columns.tolist())
print(patient_df.columns.tolist())

['Month', 'Case_No', 'DOB', 'Nationality', 'Gender', 'DoctorLicense', 'DoctorName', 'Doctor Type', 'Doctor Status', 'CMI Value', 'Specialty', 'Insurance/Payer', 'InsurancePlanName', 'Payer Mix', 'Case type', 'LOS', 'Severity', 'Surgical Mix', 'Discharge Time', 'Discharge Before 12PM', 'Revenue']
['Patient_ID', 'Age', 'Gender', 'Department', 'Diagnosis', 'Severity_Level', 'Admission_Date', 'Discharge_Date', 'Length_of_Stay_Days', 'Wait_Time_Minutes', 'Doctor_ID', 'Insurance_Type', 'Treatment_Cost_USD', 'Readmission_Flag', 'Outcome']

In [10]:
hospital_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 21 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Month                  500 non-null    str
 1   Case_No                500 non-null    float64
 2   DOB                    500 non-null    float64
 3   Nationality            500 non-null    str
 4   Gender                 500 non-null    str
 5   DoctorLicense          500 non-null    str
 6   DoctorName             500 non-null    str
 7   Doctor Type            500 non-null    str
 8   Doctor Status          500 non-null    str
 9   CMI Value              500 non-null    float64
 10  Specialty              500 non-null    str
 11  Insurance/Payer        500 non-null    str
 12  InsurancePlanName      428 non-null    str
 13  Payer Mix              500 non-null    str
 14  Case type              500 non-null    str
 15  LOS                    500 non-null    float64
 16  Severity               500 non-null    float64
 17  Surgical Mix           500 non-null    str
 18  Discharge Time         262 non-null    str
 19  Discharge Before 12PM  262 non-null    str
 20  Revenue                500 non-null    float64
dtypes: float64(6), str(15)
memory usage: 82.2 KB

In [11]:
patient_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 15 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Patient_ID           100000 non-null  str
 1   Age                  100000 non-null  int64
 2   Gender               100000 non-null  str
 3   Department           100000 non-null  str
 4   Diagnosis            100000 non-null  str
 5   Severity_Level       100000 non-null  str
 6   Admission_Date       100000 non-null  str
 7   Discharge_Date       100000 non-null  str
 8   Length_of_Stay_Days  100000 non-null  int64
 9   Wait_Time_Minutes    100000 non-null  int64
 10  Doctor_ID            100000 non-null  str
 11  Insurance_Type       100000 non-null  str
 12  Treatment_Cost_USD   100000 non-null  int64
 13  Readmission_Flag     100000 non-null  int64
 14  Outcome              100000 non-null  str
dtypes: int64(5), str(10)
memory usage: 11.4 MB

In [12]:
hospital_df.describe(include="all")

,Month,Case_No,DOB,Nationality,Gender,DoctorLicense,DoctorName,Doctor Type,Doctor Status,CMI Value,Specialty,Insurance/Payer,InsurancePlanName,Payer Mix,Case type,LOS,Severity,Surgical Mix,Discharge Time,Discharge Before 12PM,Revenue
count,500,5.000000e+02,500.000,500,500,500,500,500,500,500.000000,500,500,428,500,500,500.000,500.000,500,262,262,500.000
unique,12,NaN,NaN,14,2,10,10,3,2,NaN,10,6,9,2,3,NaN,NaN,2,228,2,NaN
top,2025-02-01,NaN,NaN,India,M,FGH234,Dr. Hana Suzuki,Specialist,Active,NaN,General Surgery,PureWin Insurance,Advance,Insurance,OP,NaN,NaN,Medical,07:00:00,No,NaN
freq,56,NaN,NaN,101,290,70,70,236,405,NaN,70,211,84,428,308,NaN,NaN,300,2,141,NaN
mean,NaN,1.237317e+08,1984.408,NaN,NaN,NaN,NaN,NaN,NaN,1.037098,NaN,NaN,NaN,NaN,NaN,1.284,1.782,NaN,NaN,NaN,17046.728
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
min,NaN,1.234584e+08,1955.000,NaN,NaN,NaN,NaN,NaN,NaN,0.710000,NaN,NaN,NaN,NaN,NaN,0.000,1.000,NaN,NaN,NaN,99.000
25%,NaN,1.235896e+08,1975.000,NaN,NaN,NaN,NaN,NaN,NaN,0.960000,NaN,NaN,NaN,NaN,NaN,0.000,1.000,NaN,NaN,NaN,830.000
50%,NaN,1.237408e+08,1987.000,NaN,NaN,NaN,NaN,NaN,NaN,1.035000,NaN,NaN,NaN,NaN,NaN,0.000,2.000,NaN,NaN,NaN,1628.500
75%,NaN,1.238734e+08,1996.000,NaN,NaN,NaN,NaN,NaN,NaN,1.110250,NaN,NaN,NaN,NaN,NaN,3.000,2.000,NaN,NaN,NaN,15310.500
max,NaN,1.239995e+08,2005.000,NaN,NaN,NaN,NaN,NaN,NaN,1.394000,NaN,NaN,NaN,NaN,NaN,7.000,3.000,NaN,NaN,NaN,160962.000

In [13]:
patient_df.describe(include="all")

,Patient_ID,Age,Gender,Department,Diagnosis,Severity_Level,Admission_Date,Discharge_Date,Length_of_Stay_Days,Wait_Time_Minutes,Doctor_ID,Insurance_Type,Treatment_Cost_USD,Readmission_Flag,Outcome
count,100000,100000.00000,100000,100000,100000,100000,100000,100000,100000.00000,100000.00000,100000,100000,100000.0000,100000.00000,100000
unique,100000,NaN,2,10,10,4,100000,100000,NaN,NaN,500,4,NaN,NaN,4
top,PAT000001,NaN,Male,Dermatology,Heart Disease,Low,2026-05-02 06:06:47.667330,2026-05-04 06:06:47.667330,NaN,NaN,DOC0169,Government,NaN,NaN,Recovered
freq,1,NaN,50406,10205,10218,40094,1,1,NaN,NaN,252,25075,NaN,NaN,68568
mean,NaN,47.42622,NaN,NaN,NaN,NaN,NaN,NaN,5.35733,152.03647,NaN,NaN,4893.8949,0.07477,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
min,NaN,0.00000,NaN,NaN,NaN,NaN,NaN,NaN,1.00000,5.00000,NaN,NaN,100.0000,0.00000,NaN
25%,NaN,23.00000,NaN,NaN,NaN,NaN,NaN,NaN,2.00000,78.00000,NaN,NaN,662.0000,0.00000,NaN
50%,NaN,47.00000,NaN,NaN,NaN,NaN,NaN,NaN,3.00000,152.00000,NaN,NaN,2142.0000,0.00000,NaN
75%,NaN,71.00000,NaN,NaN,NaN,NaN,NaN,NaN,7.00000,226.00000,NaN,NaN,5002.2500,0.00000,NaN
max,NaN,95.00000,NaN,NaN,NaN,NaN,NaN,NaN,30.00000,300.00000,NaN,NaN,49999.0000,1.00000,NaN

In [14]:
hospital_df.isnull().sum()

Month                      0
Case_No                    0
DOB                        0
Nationality                0
Gender                     0
                        ...
Severity                   0
Surgical Mix               0
Discharge Time           238
Discharge Before 12PM    238
Revenue                    0
Length: 21, dtype: int64

In [15]:
patient_df.isnull().sum()

Patient_ID            0
Age                   0
Gender                0
Department            0
Diagnosis             0
                     ..
Doctor_ID             0
Insurance_Type        0
Treatment_Cost_USD    0
Readmission_Flag      0
Outcome               0
Length: 15, dtype: int64

In [16]:
print("Hospital Dataset:", hospital_df.duplicated().sum())

Hospital Dataset: 0

In [17]:
print("Patient Dataset:", patient_df.duplicated().sum())

Patient Dataset: 0

In [18]:
patient_df.dtypes

Patient_ID              str
Age                   int64
Gender                  str
Department              str
Diagnosis               str
                      ...
Doctor_ID               str
Insurance_Type          str
Treatment_Cost_USD    int64
Readmission_Flag      int64
Outcome                 str
Length: 15, dtype: object

In [19]:
hospital_df.dtypes

Month                        str
Case_No                  float64
DOB                      float64
Nationality                  str
Gender                       str
                          ...
Severity                 float64
Surgical Mix                 str
Discharge Time               str
Discharge Before 12PM        str
Revenue                  float64
Length: 21, dtype: object

In [20]:
hospital_df.to_csv(
    "../data/raw/hospital_raw_data.csv",
    index=False
)

patient_df.to_csv(
    "../data/raw/patient_raw_data.csv",
    index=False
)

# Module 1 Conclusion

Two healthcare datasets were successfully collected and inspected.

The Hospital Operations dataset contains operational, financial, insurance, doctor, and revenue information.

The Patient Operations dataset contains patient demographics, department, admission, discharge, diagnosis, treatment cost, readmission, and outcome information.

Since the datasets do not share a common unique identifier, they cannot be merged at the row level without compromising data integrity. Instead, both datasets will be cleaned independently and later integrated logically through common KPIs and Tableau dashboards.

This approach preserves data quality while satisfying the project requirement of integrating healthcare datasets.