# KPI Engineering

In [1]:
import pandas as pd

master = pd.read_csv("Processed_Data/Fact_Admissions_Clean.csv")

master.head()

,admission_id,admission_date,discharge_date,admission_type,admission_status,patient_id,gender,date_of_birth,blood_group,city,...,total_beds,bed_number,bed_status,disease_name,disease_category,length_of_stay,admission_year,admission_month,admission_quarter,admission_day
0,1,2020-02-25,2020-02-27,Emergency,Discharged,166,Male,1954-11-02,A-,North Dorisland,...,10,6-1,Available,Anemia,Hematological,2,2020,February,1,Tuesday
1,2,2022-02-22,2022-03-04,Elective,Discharged,8622,Female,1988-02-25,AB+,West Susan,...,15,21-2,Available,Fracture Femur,Orthopedic,10,2022,February,1,Tuesday
2,3,2021-02-03,2021-02-09,Elective,Discharged,23976,Male,1944-03-02,A-,North Erik,...,15,2-1,Available,Chronic Obstructive Pulmonary Disease,Respiratory,6,2021,February,1,Wednesday
3,4,2021-12-31,2022-01-05,Elective,Discharged,16635,Male,2017-08-19,A+,Maldonadoton,...,20,10-8,Available,Acute Myocardial Infarction,Cardiac,5,2021,December,4,Friday
4,5,2022-07-02,2022-07-07,Elective,Discharged,10654,Male,2015-05-06,A+,Port Stephanie,...,20,11-17,Available,Hypertension,Cardiac,5,2022,July,3,Saturday

In [2]:
doctor = pd.read_csv("Processed_Data/Dim_Doctor.csv")
ward = pd.read_csv("Processed_Data/Dim_Ward.csv")
bed = pd.read_csv("Processed_Data/bed.csv")

In [3]:
print(master.shape)

master.info()

(45000, 27)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45000 entries, 0 to 44999
Data columns (total 27 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   admission_id       45000 non-null  int64
 1   admission_date     45000 non-null  object
 2   discharge_date     45000 non-null  object
 3   admission_type     45000 non-null  object
 4   admission_status   45000 non-null  object
 5   patient_id         45000 non-null  int64
 6   gender             45000 non-null  object
 7   date_of_birth      45000 non-null  object
 8   blood_group        45000 non-null  object
 9   city               45000 non-null  object
 10  contact_number     45000 non-null  object
 11  department_name    45000 non-null  object
 12  department_type    45000 non-null  object
 13  floor_number       45000 non-null  int64
 14  status             45000 non-null  object
 15  ward_name          45000 non-null  object
 16  ward_type          45000 non-null  object
 17  total_beds         45000 non-null  int64
 18  bed_number         45000 non-null  object
 19  bed_status         45000 non-null  object
 20  disease_name       45000 non-null  object
 21  disease_category   45000 non-null  object
 22  length_of_stay     45000 non-null  int64
 23  admission_year     45000 non-null  int64
 24  admission_month    45000 non-null  object
 25  admission_quarter  45000 non-null  int64
 26  admission_day      45000 non-null  object
dtypes: int64(7), object(20)
memory usage: 9.3+ MB

In [4]:
total_patients = master["patient_id"].nunique()

print("Total Patients:", total_patients)

Total Patients: 23275

In [5]:
total_admissions = master["admission_id"].nunique()

print("Total Admissions:", total_admissions)

Total Admissions: 45000

In [6]:
master["admission_date"] = pd.to_datetime(master["admission_date"])
master["discharge_date"] = pd.to_datetime(master["discharge_date"])

In [7]:
total_wards = master["ward_name"].nunique()

print("Total Wards:", total_wards)

Total Wards: 27

In [8]:
average_los = round(master["length_of_stay"].mean(), 2)

print("Average Length of Stay:", average_los)

Average Length of Stay: 5.16

In [9]:
department_admissions = (
    master.groupby("department_name")
    .size()
    .reset_index(name="Total Admissions")
    .sort_values(by="Total Admissions", ascending=False)
)

department_admissions

     department_name  Total Admissions
5            Surgery             10126
0          Emergency              8777
4         Pediatrics              8438
2  Internal Medicine              7695
3        Orthopedics              5924
1                ICU              4040

In [10]:
disease_analysis = (
    master.groupby("disease_name")
    .size()
    .reset_index(name="Total Admissions")
    .sort_values(by="Total Admissions", ascending=False)
)

disease_analysis

                             disease_name  Total Admissions
16                                 Stroke              2300
15                                 Sepsis              2297
6   Chronic Obstructive Pulmonary Disease              2289
8                          Fracture Femur              2288
0             Acute Myocardial Infarction              2282
1              Acute Respiratory Distress              2275
9                              Gallstones              2271
18                Urinary Tract Infection              2259
17                           Tuberculosis              2256
14                  Road Traffic Accident              2253
19                            Viral Fever              2252
5                  Chronic Kidney Disease              2251
3                            Appendicitis              2245
11                           Hypertension              2243
12                      Neonatal Jaundice              2239
2                                  Anemia              2235
13                              Pneumonia              2197
10                                 Hernia              2195
7                       Diabetes Mellitus              2189
4                                COVID-19              2184

In [11]:
monthly_admissions = (
    master.groupby("admission_month")
    .size()
    .reset_index(name="Total Admissions")
)

monthly_admissions

   admission_month  Total Admissions
0            April              3727
1           August              3751
2         December              3774
3         February              3499
4          January              3781
5             July              3838
6             June              3672
7            March              3874
8              May              3846
9         November              3646
10         October              3819
11       September              3773

In [12]:
gender_distribution = (
    master.groupby("gender")
    .size()
    .reset_index(name="Patients")
)

gender_distribution

   gender  Patients
0  Female     20058
1    Male     24031
2   Other       911

In [13]:
admission_type = (
    master.groupby("admission_type")
    .size()
    .reset_index(name="Admissions")
)

admission_type

  admission_type  Admissions
0       Elective       26923
1      Emergency       18077

In [14]:
bed_status = (
    master.groupby("bed_status")
    .size()
    .reset_index(name="Beds")
)

bed_status

  bed_status   Beds
0  Available  45000

In [15]:
department_admissions.to_csv("KPI_Data/Department_Admissions.csv", index=False)

disease_analysis.to_csv("KPI_Data/Disease_Analysis.csv", index=False)

monthly_admissions.to_csv("KPI_Data/Monthly_Admissions.csv", index=False)

gender_distribution.to_csv("KPI_Data/Gender_Distribution.csv", index=False)

admission_type.to_csv("KPI_Data/Admission_Type.csv", index=False)

bed_status.to_csv("KPI_Data/Bed_Status.csv", index=False)

print(" KPI files saved successfully!")

 KPI files saved successfully!

In [16]:
admissions_year = (
    master.groupby("admission_year")
    .size()
    .reset_index(name="Total_Admissions")
)

admissions_year.to_csv("KPI_Data/Admissions_Year.csv", index=False)
admissions_year.head()

   admission_year  Total_Admissions
0            2020              7469
1            2021              7539
2            2022              7517
3            2023              7351
4            2024              7529

In [17]:
admissions_quarter = (
    master.groupby("admission_quarter")
    .size()
    .reset_index(name="Total_Admissions")
)

admissions_quarter.to_csv("KPI_Data/Admissions_Quarter.csv", index=False)
admissions_quarter.head()

   admission_quarter  Total_Admissions
0                  1             11154
1                  2             11245
2                  3             11362
3                  4             11239

In [18]:
admissions_day = (
    master.groupby("admission_day")
    .size()
    .reset_index(name="Total_Admissions")
)

admissions_day.to_csv("KPI_Data/Admissions_Day.csv", index=False)
admissions_day.head()

  admission_day  Total_Admissions
0        Friday              6494
1        Monday              6424
2      Saturday              6488
3        Sunday              6328
4      Thursday              6273

In [19]:
ward_utilization = (
    master.groupby("ward_name")
    .size()
    .reset_index(name="Admissions")
)

ward_utilization.to_csv("KPI_Data/Ward_Utilization.csv", index=False)
ward_utilization.head()

          ward_name  Admissions
0  Emergency Ward 1        1265
1  Emergency Ward 2        1867
2  Emergency Ward 3        1206
3  Emergency Ward 4        2227
4  Emergency Ward 5        2212

In [20]:
city_patients = (
    master.groupby("city")
    .size()
    .reset_index(name="Patients")
)

city_patients.to_csv("KPI_Data/City_Patients.csv", index=False)
city_patients.head()

           city  Patients
0     Aaronberg         2
1  Aaronborough         1
2    Aaronburgh         2
3     Aaronbury         3
4  Aaronchester         1

In [21]:
blood_group = (
    master.groupby("blood_group")
    .size()
    .reset_index(name="Patients")
)

blood_group.to_csv("KPI_Data/Blood_Group.csv", index=False)
blood_group.head()

  blood_group  Patients
0          A+      5644
1          A-      5676
2         AB+      5589
3         AB-      5737
4          B+      5462

In [22]:
disease_category = (
    master.groupby("disease_category")
    .size()
    .reset_index(name="Patients")
)

disease_category.to_csv("KPI_Data/Disease_Category.csv", index=False)
disease_category.head()

  disease_category  Patients
0          Cardiac      4525
1        Endocrine      2189
2    Hematological      2235
3       Infectious     11248
4     Neurological      2300

In [25]:
master = master.sort_values(["patient_id", "admission_date"])

master["previous_discharge"] = master.groupby("patient_id")["discharge_date"].shift(1)

master["days_after_discharge"] = (
    master["admission_date"] - master["previous_discharge"]
).dt.days

master["readmission"] = master["days_after_discharge"].apply(
    lambda x: "Yes" if pd.notna(x) and x <= 30 else "No"
)

In [26]:
readmission_summary = (
    master.groupby("readmission")
          .size()
          .reset_index(name="Total_Patients")
)

readmission_summary

  readmission  Total_Patients
0          No           43880
1         Yes            1120

In [27]:
total_admissions = len(master)

readmission_rate = (
    master["readmission"].eq("Yes").sum() / total_admissions
) * 100

print(f"Readmission Rate: {readmission_rate:.2f}%")

Readmission Rate: 2.49%

In [28]:
readmission_summary.to_csv(
    "KPI_Data/Readmission_Summary.csv",
    index=False
)

print("✅ Readmission_Summary.csv saved successfully!")

✅ Readmission_Summary.csv saved successfully!

In [36]:
# Resource KPIs

total_beds = ward["total_beds"].sum()

total_doctors = doctor["doctor_id"].nunique()

avg_doctor_experience = round(doctor["experience_years"].mean(), 2)

available_beds = bed[bed["bed_status"] == "Available"]["bed_id"].count()

occupied_beds = bed[bed["bed_status"] == "Occupied"]["bed_id"].count()

bed_occupancy_rate = round((occupied_beds / total_beds) * 100, 2)

In [39]:
kpi_summary = pd.DataFrame({

    "KPI":[
        "Total Admissions",
        "Total Patients",
        "Total Departments",
        "Total Wards",
        "Average Length of Stay",
        "Readmission Rate (%)",
        "Total Beds",
        "Total Doctors",
        "Average Doctor Experience",
        "Available Beds",
        "Occupied Beds",
        "Bed Occupancy Rate (%)"
    ],

    "Value":[
        total_admissions,
        total_patients,
        master["department_name"].nunique(),
        total_wards,
        average_los,
        round((master["readmission"]=="Yes").mean()*100,2),
        total_beds,
        total_doctors,
        avg_doctor_experience,
        available_beds,
        occupied_beds,
        bed_occupancy_rate
    ]

})

In [40]:
kpi_summary.to_csv("KPI_Data/KPI_Summary.csv", index=False)

print("KPI_Summary.csv saved successfully!")

KPI_Summary.csv saved successfully!