In [1]:
import pandas as pd
import numpy as np

patients = pd.read_csv("diabetic_data.csv")
hospital = pd.read_csv("HospInfo.csv")
provider = pd.read_csv("pos2011.csv")
mapping = pd.read_csv("IDS_mapping.csv")

C:\Users\smile\AppData\Local\Temp\ipykernel_6048\3562865762.py:6: DtypeWarning: Columns (7,8,13,15,16,17,23,29,34,35,43,47,48,58,59,60,61,62,80,81,112,118,119,120,122,130,134,138,173,203,204,205,209,210,225,226,228,229,230,283,338,339,342,344,346,347,349,351,353,354,356,358,360,362,363,365,366,369,371,373,380,382,383,385,386,389,391,393,394,397,401,403,405,407,409,410,412,416,417,419,425,426,427,428,431,432,435,439,441,442,444,446,448,485,494,497) have mixed types. Specify dtype option on import or set low_memory=False.
  provider = pd.read_csv("pos2011.csv")

In [2]:
patients = patients.drop_duplicates()
patients.replace("?", np.nan, inplace=True)

In [3]:
patients = patients.sample(n=5000, random_state=42).reset_index(drop=True)

In [6]:
hospital = hospital[
[
'Provider ID',
'Hospital Name',
'City',
'State',
'Hospital Type',
'Hospital Ownership',
'Emergency Services',
'Hospital overall rating'
]]

In [5]:
provider = provider[
[
'PRVDR_NUM',
'FAC_NAME',
'CITY_NAME',
'STATE_CD',
'BED_CNT',
'EMPLEE_CNT'
]]

In [7]:
hospital = hospital.head(5000).reset_index(drop=True)
provider = provider.head(5000).reset_index(drop=True)

In [8]:
provider.rename(columns={
    'FAC_NAME':'Facility Name',
    'CITY_NAME':'Provider City',
    'STATE_CD':'Provider State'
}, inplace=True)

In [9]:
patients["temp_id"] = patients.index
hospital["temp_id"] = hospital.index
provider["temp_id"] = provider.index

In [10]:
final = patients.merge(
    hospital,
    on="temp_id",
    how="left"
)

final = final.merge(
    provider,
    on="temp_id",
    how="left"
)

In [11]:
final.drop("temp_id", axis=1, inplace=True)

In [12]:
final.to_csv("hospital_cleaned.csv", index=False)

In [13]:
final.shape

(5000, 64)

In [14]:
patients.shape

(5000, 51)

In [15]:
hospital.shape

(4812, 9)

In [16]:
provider.shape

(5000, 7)

In [17]:
final.shape

(5000, 64)

In [18]:
hospital.columns.tolist()

['Provider ID',
 'Hospital Name',
 'City',
 'State',
 'Hospital Type',
 'Hospital Ownership',
 'Emergency Services',
 'Hospital overall rating',
 'temp_id']

In [19]:
provider.columns.tolist()

['PRVDR_NUM',
 'Facility Name',
 'Provider City',
 'Provider State',
 'BED_CNT',
 'EMPLEE_CNT',
 'temp_id']

In [20]:
final.tail()

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,...,Hospital Type,Hospital Ownership,Emergency Services,Hospital overall rating,PRVDR_NUM,Facility Name,Provider City,Provider State,BED_CNT,EMPLEE_CNT
4995,110096790,33502212,Caucasian,Male,[50-60),NaN,6,1,7,12,...,NaN,NaN,NaN,NaN,045359,ABINGTON PLACE HEALTH AND REHAB CENTER,LITTLE ROCK,AR,120.0,NaN
4996,402583472,141357506,AfricanAmerican,Male,[50-60),NaN,7,3,7,6,...,NaN,NaN,NaN,NaN,045360,CLARKSVILLE COMMUNITY HEALTH AND REHABILITATIO...,CLARKSVILLE,AR,105.0,NaN
4997,282442506,45759951,Caucasian,Female,[40-50),NaN,1,1,7,3,...,NaN,NaN,NaN,NaN,045361,BENTONVILLE MANOR NURSING HOME,BENTONVILLE,AR,95.0,NaN
4998,161139018,112510251,Caucasian,Female,[40-50),NaN,5,1,1,3,...,NaN,NaN,NaN,NaN,045362,OSCEOLA HEALTHCARE,OSCEOLA,AR,115.0,NaN
4999,100977444,98312472,Caucasian,Female,[70-80),NaN,6,1,17,5,...,NaN,NaN,NaN,NaN,045363,COVINGTON COURT HEALTH AND REHABILITATION CENTER,FORT SMITH,AR,140.0,NaN

In [21]:
final[['Hospital Name','Hospital Type','Hospital Ownership']].head(20)

,Hospital Name,Hospital Type,Hospital Ownership
0,MARSHALL MEDICAL CENTER SOUTH,Acute Care Hospitals,Government - Hospital District or Authority
1,DEKALB REGIONAL MEDICAL CENTER,Acute Care Hospitals,Proprietary
2,WEDOWEE HOSPITAL,Acute Care Hospitals,Government - Hospital District or Authority
3,HALE COUNTY HOSPITAL,Acute Care Hospitals,Government - Local
4,CRESTWOOD MEDICAL CENTER,Acute Care Hospitals,Proprietary
5,CHOCTAW GENERAL HOSPITAL,Critical Access Hospitals,Voluntary non-profit - Private
6,YUKON KUSKOKWIM DELTA REG HOSPITAL,Acute Care Hospitals,Tribal
7,NORTON SOUND REGIONAL HOSPITAL,Critical Access Hospitals,Tribal
8,KANAKANAK HOSPITAL,Critical Access Hospitals,Voluntary non-profit - Private
9,MANIILAQ HEALTH CENTER,Critical Access Hospitals,Tribal
10,FORT DEFIANCE INDIAN HOSPITAL,Acute Care Hospitals,Government - Federal
11,TUBA CITY REGIONAL HEALTH CARE CORPORATION,Acute Care Hospitals,Voluntary non-profit - Other
12,SELLS HOSPITAL,Acute Care Hospitals,Tribal
13,SAN CARLOS APACHE HEALTHCARE,Acute Care Hospitals,Government - Federal
14,CHINLE COMPREHENSIVE HEALTH CARE FACILITY,Acute Care Hospitals,Government - Federal
15,HOPI HEALTH CARE CENTER,Critical Access Hospitals,Tribal
16,HUHU KAM MEMORIAL HOSPITAL,Critical Access Hospitals,Government - Hospital District or Authority
17,SAGE MEMORIAL HOSPITAL,Critical Access Hospitals,Voluntary non-profit - Private
18,CHI-ST VINCENT INFIRMARY,Acute Care Hospitals,Voluntary non-profit - Private
19,SPARKS MEDICAL CENTER - VAN BUREN,Acute Care Hospitals,Proprietary

In [22]:
hospital.head(5000)

,Provider ID,Hospital Name,City,State,Hospital Type,Hospital Ownership,Emergency Services,Hospital overall rating,temp_id
0,10005,MARSHALL MEDICAL CENTER SOUTH,BOAZ,AL,Acute Care Hospitals,Government - Hospital District or Authority,True,3,0
1,10012,DEKALB REGIONAL MEDICAL CENTER,FORT PAYNE,AL,Acute Care Hospitals,Proprietary,True,3,1
2,10032,WEDOWEE HOSPITAL,WEDOWEE,AL,Acute Care Hospitals,Government - Hospital District or Authority,True,4,2
3,10095,HALE COUNTY HOSPITAL,GREENSBORO,AL,Acute Care Hospitals,Government - Local,True,Not Available,3
4,10131,CRESTWOOD MEDICAL CENTER,HUNTSVILLE,AL,Acute Care Hospitals,Proprietary,True,3,4
...,...,...,...,...,...,...,...,...,...
4807,450617,CLEAR LAKE REGIONAL MEDICAL CENTER,WEBSTER,TX,Acute Care Hospitals,Proprietary,True,3,4807
4808,520194,ORTHOPAEDIC HOSPITAL OF WISCONSIN,GLENDALE,WI,Acute Care Hospitals,Voluntary non-profit - Other,False,Not Available,4808
4809,491302,CARILION GILES COMMUNITY HOSPITAL,PEARISBURG,VA,Critical Access Hospitals,Voluntary non-profit - Private,True,4,4809
4810,510012,PLEASANT VALLEY HOSPITAL,POINT PLEASANT,WV,Acute Care Hospitals,Voluntary non-profit - Private,True,3,4810
4811,490053,JOHNSTON MEMORIAL HOSPITAL,ABINGDON,VA,Acute Care Hospitals,Voluntary non-profit - Private,True,3,4811

In [23]:
hospital = hospital.sample(
    n=len(patients),
    replace=True,
    random_state=42
).reset_index(drop=True)

In [24]:
provider = provider.sample(
    n=len(patients),
    replace=True,
    random_state=42
).reset_index(drop=True)

In [25]:
patients["temp_id"] = range(len(patients))
hospital["temp_id"] = range(len(hospital))
provider["temp_id"] = range(len(provider))

In [26]:
final = patients.merge(
    hospital,
    on="temp_id",
    how="left"
)

final = final.merge(
    provider,
    on="temp_id",
    how="left"
)

In [27]:
final.drop("temp_id", axis=1, inplace=True)

In [28]:
final.shape

(5000, 64)

In [29]:
final[
[
'Hospital Name',
'Hospital Type',
'Hospital Ownership',
'Emergency Services',
'Hospital overall rating',
'Facility Name',
'Provider City',
'BED_CNT'
]
].head(20)

,Hospital Name,Hospital Type,Hospital Ownership,Emergency Services,Hospital overall rating,Facility Name,Provider City,BED_CNT
0,PARRISH MEDICAL CENTER,Acute Care Hospitals,Government - Hospital District or Authority,True,4,MARENGO FAMILY HEALTH CENTER,LINDEN,NaN
1,FAULKTON AREA MEDICAL CENTER,Critical Access Hospitals,Voluntary non-profit - Private,True,Not Available,SUN CITY ENDOSCOPY CENTER,SUN CITY,NaN
2,CHILDREN'S SPECIALIZED HOSPITAL,Childrens,Voluntary non-profit - Private,False,Not Available,DESERT COVE NURSING CENTER,CHANDLER,120.0
3,JOHN MUIR MEDICAL CENTER - CONCORD CAMPUS,Acute Care Hospitals,Voluntary non-profit - Private,True,4,DOUGLAS MEDICAL CLINIC,HORTON,NaN
4,KNAPP MEDICAL CENTER,Acute Care Hospitals,Voluntary non-profit - Private,True,4,BMA BLYTHEVILLE,BLYTHEVILLE,NaN
5,TRISTAR HORIZON MEDICAL CENTER,Acute Care Hospitals,Proprietary,True,3,OLSTEN HOME HLTH CARE INC,PHOENIX,NaN
6,FAXTON-ST LUKE'S HEALTHCARE,Acute Care Hospitals,Voluntary non-profit - Private,True,1,PARK AVENUE HEALTH AND REHABILITATION CENTER,TUCSON,200.0
7,CHRISTUS ST VINCENT REGIONAL MEDICAL CENTER,Acute Care Hospitals,Voluntary non-profit - Private,True,2,TUCSON PSYCH INSTIT INC,TUCSON,54.0
8,SOUTHWEST MS REGIONAL MEDICAL CENTER,Acute Care Hospitals,Government - Local,True,2,RUSSELLVILLE HOSPITAL,RUSSELLVILLE,100.0
9,LAKEVIEW REGIONAL MEDICAL CENTER,Acute Care Hospitals,Proprietary,True,3,NORTH RIVER SURGICAL CENTER INC,TUSCALOOSA,NaN
10,COLQUITT REGIONAL MEDICAL CENTER,Acute Care Hospitals,Government - Hospital District or Authority,True,3,CHEROKEE CLINIC,CENTRE,NaN
11,HAYES GREEN BEACH MEMORIAL HOSPITAL,Critical Access Hospitals,Voluntary non-profit - Other,True,3,SCOTTSDALE COMMUNITY HOSPITAL,SCOTTSDALE,94.0
12,CLAIBORNE COUNTY HOSPITAL,Critical Access Hospitals,Government - Local,False,Not Available,ARIZONA SPINE AND JOINT HOSPITAL,MESA,23.0
13,HOAG ORTHOPEDIC INSTITUTE,Acute Care Hospitals,Proprietary,False,Not Available,GOLDEN LIVING CENTER - PELL CITY,PELL CITY,94.0
14,"LAKEWAY REGIONAL MEDICAL CENTER, LLC",Acute Care Hospitals,Proprietary,True,3,SPARKMAN COMMUNITY CLINIC,SPARKMAN,NaN
15,MERCY HOSPITAL OF DEFIANCE,Acute Care Hospitals,Proprietary,True,4,NURSEFINDERS OF TUCSON,TUCSON,NaN
16,HENRICO DOCTORS' HOSPITAL,Acute Care Hospitals,Voluntary non-profit - Other,True,4,DALLAS COUNTY HOSPITAL,FORDYCE,49.0
17,WARREN MEMORIAL HOSPITAL,Critical Access Hospitals,Government - Local,True,Not Available,RILEYS OAK HILL MANOR NORTH,NORTH LITTLE ROCK,224.0
18,NORTH SUBURBAN MEDICAL CENTER,Acute Care Hospitals,Voluntary non-profit - Private,True,3,GREASEWOOD CLINIC,GANADO,NaN
19,WASHINGTON COUNTY REGIONAL MEDICAL CENTER,Acute Care Hospitals,Government - Hospital District or Authority,True,3,"FAMILY HEALTH CARE CLINIC, INC",MUSCLE SHOALS,NaN

In [30]:
final.isnull().sum().sort_values(ascending=False)

weight                     4830
max_glu_serum              4740
EMPLEE_CNT                 4610
A1Cresult                  4154
BED_CNT                    3280
                           ...
Hospital overall rating       0
Facility Name                 0
PRVDR_NUM                     0
Provider State                0
Provider City                 0
Length: 64, dtype: int64

In [31]:
final.duplicated().sum()

np.int64(0)

In [32]:
final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 64 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   encounter_id              5000 non-null   int64
 1   patient_nbr               5000 non-null   int64
 2   race                      4887 non-null   object
 3   gender                    5000 non-null   object
 4   age                       5000 non-null   object
 5   weight                    170 non-null    object
 6   admission_type_id         5000 non-null   int64
 7   discharge_disposition_id  5000 non-null   int64
 8   admission_source_id       5000 non-null   int64
 9   time_in_hospital          5000 non-null   int64
 10  payer_code                3033 non-null   object
 11  medical_specialty         2565 non-null   object
 12  num_lab_procedures        5000 non-null   int64
 13  num_procedures            5000 non-null   int64
 14  num_medications           5000 non-null   int64
 15  number_outpatient         5000 non-null   int64
 16  number_emergency          5000 non-null   int64
 17  number_inpatient          5000 non-null   int64
 18  diag_1                    4999 non-null   object
 19  diag_2                    4984 non-null   object
 20  diag_3                    4927 non-null   object
 21  number_diagnoses          5000 non-null   int64
 22  max_glu_serum             260 non-null    object
 23  A1Cresult                 846 non-null    object
 24  metformin                 5000 non-null   object
 25  repaglinide               5000 non-null   object
 26  nateglinide               5000 non-null   object
 27  chlorpropamide            5000 non-null   object
 28  glimepiride               5000 non-null   object
 29  acetohexamide             5000 non-null   object
 30  glipizide                 5000 non-null   object
 31  glyburide                 5000 non-null   object
 32  tolbutamide               5000 non-null   object
 33  pioglitazone              5000 non-null   object
 34  rosiglitazone             5000 non-null   object
 35  acarbose                  5000 non-null   object
 36  miglitol                  5000 non-null   object
 37  troglitazone              5000 non-null   object
 38  tolazamide                5000 non-null   object
 39  examide                   5000 non-null   object
 40  citoglipton               5000 non-null   object
 41  insulin                   5000 non-null   object
 42  glyburide-metformin       5000 non-null   object
 43  glipizide-metformin       5000 non-null   object
 44  glimepiride-pioglitazone  5000 non-null   object
 45  metformin-rosiglitazone   5000 non-null   object
 46  metformin-pioglitazone    5000 non-null   object
 47  change                    5000 non-null   object
 48  diabetesMed               5000 non-null   object
 49  readmitted                5000 non-null   object
 50  Provider ID               5000 non-null   int64
 51  Hospital Name             5000 non-null   object
 52  City                      5000 non-null   object
 53  State                     5000 non-null   object
 54  Hospital Type             5000 non-null   object
 55  Hospital Ownership        5000 non-null   object
 56  Emergency Services        5000 non-null   bool
 57  Hospital overall rating   5000 non-null   object
 58  PRVDR_NUM                 5000 non-null   object
 59  Facility Name             5000 non-null   object
 60  Provider City             5000 non-null   object
 61  Provider State            5000 non-null   object
 62  BED_CNT                   1720 non-null   float64
 63  EMPLEE_CNT                390 non-null    float64
dtypes: bool(1), float64(2), int64(14), object(47)
memory usage: 2.4+ MB

In [33]:
final.to_csv("hospital_cleaned.csv", index=False)

In [35]:
final.to_excel("hospital_cleaned.xlsx", index=False)

In [36]:
import os

os.listdir()

['.ipynb_checkpoints',
 'diabetic_data.csv',
 'HospInfo.csv',
 'hospitaldataset.ipynb',
 'hospital_cleaned.csv',
 'hospital_cleaned.xlsx',
 'hospital_raw_data.csv',
 'IDS_mapping.csv',
 'pos2011.csv',
 'Untitled.ipynb']

In [37]:
import os

os.path.exists("hospital_cleaned.xlsx")

True

In [38]:
test = pd.read_excel("hospital_cleaned.xlsx")

test.head()

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,...,Hospital Type,Hospital Ownership,Emergency Services,Hospital overall rating,PRVDR_NUM,Facility Name,Provider City,Provider State,BED_CNT,EMPLEE_CNT
0,110939484,19274094,Caucasian,Female,[70-80),NaN,1,1,6,11,...,Acute Care Hospitals,Government - Hospital District or Authority,True,4,013992,MARENGO FAMILY HEALTH CENTER,LINDEN,AL,NaN,NaN
1,170328306,65634327,Caucasian,Male,[50-60),NaN,1,1,1,1,...,Critical Access Hospitals,Voluntary non-profit - Private,True,Not Available,03C0001080,SUN CITY ENDOSCOPY CENTER,SUN CITY,AZ,NaN,NaN
2,245688426,100657359,Caucasian,Female,[60-70),NaN,3,6,1,4,...,Childrens,Voluntary non-profit - Private,False,Not Available,035095,DESERT COVE NURSING CENTER,CHANDLER,AZ,120.0,NaN
3,150826224,83144448,Caucasian,Male,[30-40),NaN,2,1,1,12,...,Acute Care Hospitals,Voluntary non-profit - Private,True,4,011957,DOUGLAS MEDICAL CLINIC,HORTON,AL,NaN,NaN
4,135993852,65234214,AfricanAmerican,Female,[60-70),NaN,1,2,7,1,...,Acute Care Hospitals,Voluntary non-profit - Private,True,4,042550,BMA BLYTHEVILLE,BLYTHEVILLE,AR,NaN,NaN

In [39]:
final.to_excel("hospital_cleaned.xlsx", index=False)

In [40]:
import os

print(os.path.getsize("hospital_cleaned.xlsx"))

1536160

In [41]:
final.to_excel(
    "hospital_cleaned.xlsx",
    index=False,
    engine="openpyxl"
)

In [42]:
final.to_csv("hospital_cleaned.csv", index=False)